# NOTE: Generated By HttpRunner v3.1.5
# FROM: har\login_yin_py.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/v1/login")
            .post("http://124.70.221.221:8201/api/v1/login")
            .with_headers(
                **{
                    "Content-Length": "52",
                    "Content-Type": "application/json",
                    "Host": "124.70.221.221:8201",
                    "User-Agent": "Fiddler",
                }
            )
            .with_json({"password": "123456", "username": "test"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
