# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\goods\add\add_good_status-null.yml
"""
正确加失败的场景
"""

import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseAddGoodStatusNull(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "goodsname-goodscode-merchantid-merchantname-goodsprice-stock-goodsgroupid-price-goodsstatus-code":
                [
                    ["sima_add","${goods_code()}","10003","《东方甄选》","50","100","3","30","1",0],
                    ["sima_add","${goods_code()}","10003","《东方甄选》","50","100","3","测试","1",4000],
                    ["sima_add","${goods_code()}","10003","长度测试啊长度测试啊长度测试啊长度测试啊长度测试啊长度测试啊22","50","100","1","30","1",3003],
                    ["sima_add","${goods_code()}","aaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbccccc123456","《东方甄选》","50","100","1","30","1",3003],
                    ["长度测试啊长度测试啊长度测试啊长度测试啊长度测试啊长度测试啊22","${goods_code()}","10003","《东方甄选》","50","100","1","30","1",3003],
                    ["sima_add","testdsadd","10003","《东方甄选》","50","100","1","30","1",3003],
                    ["sima_add","test","10003","《东方甄选》","50","100","1","30","1",3003],
                    ["","${goods_code()}","10003","《东方甄选》","50","100","1","30","1",3003]
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("goods 添加成功").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("添加商品-成功")
            .post("/api/v1/goods")
            .with_json(
                {
                    "goodsname": "$goodsname",
                    "goodscode": "$goodscode",
                    "merchantid": "$merchantid",
                    "merchantname": "$merchantname",
                    "goodsprice": "$goodsprice",
                    "stock": "$stock",
                    "goodsgroupid": "$goodsgroupid",
                    "price": "$price",
                    "goodsstatus": "$goodsstatus",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseAddGoodStatusNull().test_start()
