# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\goods\put\put_goods_false.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCasePutGoodsFalse(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "id-goodsname-goodscode-merchantid-merchantname-goodsprice-stock-goodsgroupid-price-goodsstatus-code": [
                    [
                        "77783",
                        "sima_add",
                        "sp_1687965910",
                        "10003",
                        "《东方甄选_大SB》",
                        "30",
                        "999999999999999999999999999999999999999999999999",
                        "3",
                        "30",
                        "1",
                        3003,
                    ],
                    [
                        "77783",
                        "sima_add",
                        "sp_1687965910",
                        "10003",
                        "《东方甄选_大SB》",
                        "30",
                        "sss",
                        "3",
                        "30",
                        "1",
                        3003,
                    ],
                    [
                        "77783",
                        "sima_add",
                        "sp_1687965910",
                        "10003",
                        "《东方甄选_大SB》",
                        "30",
                        "0.1",
                        "3",
                        "30",
                        "1",
                        3003,
                    ],
                    [
                        "77783",
                        "sima_add",
                        "sp_1009997",
                        "10003",
                        "《东方甄选_大SB》",
                        "30",
                        "11",
                        "3",
                        "30",
                        "1",
                        3003,
                    ],
                    [
                        "77783",
                        "sima_add",
                        "sp_100002sp_100002sp_100002sp_100002sp_100002sp_100002",
                        "10003",
                        "《东方甄选_大SB》",
                        "30",
                        "11",
                        "3",
                        "30",
                        "1",
                        3003,
                    ],
                    [
                        "77783",
                        "sima_add",
                        "sp_1687965910",
                        "10003",
                        "@%&（）（）—</script>—",
                        "30",
                        "11",
                        "3",
                        "30",
                        "1",
                        0,
                    ],
                    [
                        "77783",
                        "sima_add",
                        "sp_1687965910",
                        "sdsdf@$%^^%",
                        "《东方甄选_大SB》",
                        "30",
                        "11",
                        "3",
                        "30",
                        "1",
                        0,
                    ],
                    [
                        "77783",
                        "sima_add",
                        "sp_1687965910",
                        "12322125",
                        "《东方甄选_大SB》",
                        "30",
                        "11",
                        "3",
                        "30",
                        "1",
                        0,
                    ],
                    [
                        "77783",
                        "sima_add",
                        "sp_1687965910",
                        "",
                        "《东方甄选_大SB》",
                        "30",
                        "11",
                        "3",
                        "30",
                        "1",
                        0,
                    ],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("修改-失败").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("修改商品-失败场景")
            .put("/api/v1/goods/$id")
            .with_json(
                {
                    "id": "$id",
                    "goodsname": "$goodsname",
                    "goodscode": "$goodscode",
                    "merchantid": "$merchantid",
                    "merchantname": "$merchantname",
                    "goodsprice": "$goodsprice",
                    "stock": "$stock",
                    "goodsgroupid": "$goodsgroupid",
                    "price": "$price",
                    "goodsstatus": "$goodsstatus",
                }
            )
            .validate()
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCasePutGoodsFalse().test_start()
