# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\goods\put\put_goods_success.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.login_yml.login_test import TestCaseLogin as Login


class TestCasePutGoodsSuccess(HttpRunner):

    config = (
        Config("修改商品-成功")
        .variables(
            **{
                "id": 77783,
                "goodsname": "sima_add",
                "goodscode": "sp_1687965910",
                "merchantid": 10003,
                "merchantname": "《东方甄选》",
                "goodsprice": 30,
                "stock": 100,
                "goodsgroupid": 3,
                "price": 30,
                "goodsstatus": 1,
            }
        )
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(RunTestCase("取到登录的token").call(Login).export(*["token"])),
        Step(
            RunRequest("修改商品")
            .put("/api/v1/goods/$id")
            .with_json(
                {
                    "id": "$id",
                    "goodsname": "$goodsname",
                    "goodscode": "$goodscode",
                    "merchantid": "$merchantid",
                    "merchantname": "$merchantname",
                    "goodsprice": "$goodsprice",
                    "stock": "$stock",
                    "goodsgroupid": "$goodsgroupid",
                    "price": "$price",
                    "goodsstatus": "$goodsstatus",
                }
            )
            .validate()
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCasePutGoodsSuccess().test_start()
