# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\get_https.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetHttps(HttpRunner):

    config = Config("发送https请求")

    teststeps = [
        Step(
            RunRequest("请求https有证书的网站")
            .get("https://www.cnblogs.com/yoyoketang/")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseGetHttps().test_start()
