# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login_v4.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginV4(HttpRunner):

    config = Config("请求头为：application/x-www-form-urlencoded").base_url(
        "http://124.70.221.221:8201"
    )

    teststeps = [
        Step(
            RunRequest("发送请求")
            .post("/api/v4/login")
            .with_data({"username": "test1", "password": "123456"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginV4().test_start()
