# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login_vilidate.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginVilidate(HttpRunner):

    config = Config("登录").variables(**{"user": "test", "pws": "123456"})

    teststeps = [
        Step(
            RunRequest("登录成功")
            .post("${ENV(base_url)}/api/v1/login")
            .with_json({"username": "$user", "password": "$pws"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.code", 0, "code错误")
            .assert_length_equal("body.token", 40)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginVilidate().test_start()
