# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login_userinfo.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginUserinfo(HttpRunner):
    @pytest.mark.parametrize("param", Parameters({"user": "${P(data/yin_py.yml)}"}))
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("登录，取token，设置变量给下一个接口用")
        .variables(**{"user": "${ENV(user)}", "pws": "123456"})
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("先登录")
            .with_variables(**{"token": "token"})
            .post("${ENV(base_url)}/api/v1/login")
            .with_json({"username": "$user", "password": "$pws"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_length_equal("body.token", 40)
        ),
        Step(
            RunRequest("再修改个人信息")
            .post("${ENV(base_url)}/api/v1/userinfo")
            .with_headers(**{"Authorization": "Token $token"})
            .with_json(
                {"name": "test", "sex": "M", "age": 20, "mail": "283340479@qq.com"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.message", "update some data!")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginUserinfo().test_start()
