# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login_yin_py.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = (
        Config("用例描述--登录")
        .variables(**{"user": "test", "psw": "123456"})
        .base_url("http://124.70.221.221:8201")
    )

    teststeps = [
        Step(
            RunRequest("step - 登录")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("step - 登录2")
            .with_variables(**{"user": "test1", "psw": "123456"})
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("step - 登录3")
            .with_variables(**{"user": "${ENV(user)}", "psw": "123456"})
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
