# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\test_demo.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTestDemo(HttpRunner):

    config = Config("get 请求").base_url("http://124.70.221.221:8201")

    teststeps = [
        Step(
            RunRequest("demo 不带参数")
            .get("/api/test/demo")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.data[0].age", 20)
        ),
        Step(
            RunRequest("demo get带参数")
            .get("${ENV(base_url)}/api/v1/goods")
            .with_params(**{"page": 1, "size": 2})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.data[0].id", 2)
        ),
    ]


if __name__ == "__main__":
    TestCaseTestDemo().test_start()
