# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\par\userinfo.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.par.login_test import TestCaseLogin as Login


class TestCaseUserinfo(HttpRunner):

    config = Config("登录，取token，设置变量给下一个接口用").variables(
        **{"user": "test1", "pws": "123456"}
    )

    teststeps = [
        Step(RunTestCase("先登录").call(Login).export(*["token"])),
        Step(
            RunRequest("再修改个人信息")
            .post("${ENV(base_url)}/api/v1/userinfo")
            .with_headers(**{"Authorization": "Token $token"})
            .with_json(
                {"name": "$user", "sex": "M", "age": 20, "mail": "283340479@qq.com"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.message", "update some data!")
        ),
    ]


if __name__ == "__main__":
    TestCaseUserinfo().test_start()
