# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\xiugai\xinz_xiug.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseXinzXiug(HttpRunner):

    config = (
        Config("先新增商品，再修改商品")
        .base_url("${ENV(base_url)}")
        .export(*["goods_id", "goodscode"])
    )

    teststeps = [
        Step(
            RunRequest("先新增")
            .with_variables(
                **{"goodsname": "simayy_0503", "goodscode": "${goods_code()}"}
            )
            .post("/api/v1/goods")
            .with_json({"goodsname": "$goodsname", "goodscode": "$goodscode"})
            .extract()
            .with_jmespath("body.data.id", "goods_id")
            .with_jmespath("body.data.goodscode", "goodscode")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("再修改商品")
            .put("/api/v1/goods/$goods_id")
            .with_json({"goodsprice": 12.23, "goodscode": "$goodscode"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal(
                "body.data.goodsprice", "${get_goods_spid($goods_id,goodsprice)}"
            )
        ),
    ]


if __name__ == "__main__":
    TestCaseXinzXiug().test_start()
