# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login_yml\login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = (
        Config("登录-成功")
        .variables(**{"user": "test", "psw": "123456"})
        .base_url("http://124.70.221.221:8201")
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("登录成功")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "login success!")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
