# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\login_yml\login_false.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginFalse(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {"user-psw": [["xxxxyzz", "123456"], ["test123", "1234567"], ["", ""]]}
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("登录 - 失败场景").base_url("http://124.70.221.221:8201")

    teststeps = [
        Step(
            RunRequest("登录-失败")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("body.code", 3003)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginFalse().test_start()
