# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\zhuce_yml\test_chongfu_zhuce.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTestChongfuZhuce(HttpRunner):

    config = Config("重复注册").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("重复注册")
            .with_variables(**{"user": "test", "psw": "123456", "msg": "test用户已被注册"})
            .post("/api/v1/register")
            .with_headers(**{"Accept-Encoding": "gzip,deflate,br,utf-8"})
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("body.code", 2000)
            .assert_equal("body.msg", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseTestChongfuZhuce().test_start()
