# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\zhuce_yml\zhuce_yml.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseZhuce(HttpRunner):

    config = Config("注册").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("注册-引用debugtalk注册不同账户")
            .with_variables(**{"psw": "123456"})
            .post("/api/v1/register")
            .with_json({"username": "${user_register()}", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseZhuce().test_start()
