# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\hook_se_down\login.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = (
        Config("用例描述--登录")
        .variables(**{"user": "test", "psw": "123456"})
        .base_url("http://124.70.221.221:8201")
    )

    teststeps = [
        Step(
            RunRequest("step - 登录")
            .setup_hook("${hook_up()}")
            .setup_hook("${request_sign($request)}")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .teardown_hook("${hook_down()}")
            .teardown_hook("${reaponse_status($response)}")
            .validate()
            .assert_equal("status_code", 203)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
