# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcases\shangchuan\shangchuan_tu.yml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseShangchuanTu(HttpRunner):

    config = Config("上传图片").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("上传图片接口")
            .post("/api/v1/upfile/")
            .upload(**{"file": "data/test.png", "title": "司马"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseShangchuanTu().test_start()
